# Notice the v1beta3 version
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
# some metadata about the template itself
metadata:
  name: s3-template
  namespace: stone
  title: "[Autosserviço de Infraestrutura] AWS S3 Bucket"
  description: Cria um bucket s3 como autosserviço
  tags:
    - aws
    - infrastructure
    - storage
spec:
  owner: stone-payments/foundation-experience
  type: resource
  parameters:
    - title: Informações de projeto
      required: [bucket_name,account,owner]
      properties:
        bucket_name:
          pattern: '^[a-z0-9](?:[a-z0-9]|(?<=[a-z0-9])[-.](?=[a-z0-9])){1,61}[a-z0-9]$'
          title: Nome do Bucket S3
          type: string
          description: Nome único do bucket a ser deployado na AWS (lembre-se que o nome do bucket é global)
          ui:autofocus: true
        account:
          title: Contexto/Conta
          type: string
          description: Nome do contexto onde o bucket será deployado (por exemplo, o contexto banking-hml equivale à conta homolog em Banking)
          enum:
            - banking-prd
            - banking-hml
        block_public:
          title: Bloquear acesso público
          type: boolean
          description: "Para bloquear qualquer acesso público ao bucket (default: true)"
          default: true
        server_side_encryption:
          title: Ativar criptografia
          type: boolean
          description: "Criptografia server side (default: true)"
          default: true
        versioning:
          title: Ativar versionamento
          type: boolean
          description: Se o bucket terá versionamento
          default: false
          ui:autofocus: true
        owner:
          title: Time dono da aplicação
          type: string
          description: Time dono da aplicação que usará o repositório
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group

  steps:
    - id: fetch-config
      name: Fetch files
      action: fetch:plain
      input:
        url: .

    - id: account-config
      name: Parse YAML Config File
      action: custom:yaml
      input:
        path: config.yaml

    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./template
        values:
          account: ${{ parameters.account }}
          role_arn: ${{ steps.account-config.output.result.account_settings[parameters.account].role_arn }}

    - id: publish
      name: Publish
      action: publish:github:pull-request
      input:
        description: add ${{ parameters.bucket_name }}
        repoUrl: github.com?owner=sandesvitor-org&repo=infra-mock
        branchName: ${{ parameters.bucket_name }}
        title: "feat: create ${{ parameters.bucket_name }}"
        targetPath: "aws/global/${{ parameters.account }}/s3"

  output:
    links:
      - title: Ir para pull request
        url: ${{ steps.publish.output.remoteUrl }}
        icon: github
